repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace # фиксит плавающие пробелы
      - id: end-of-file-fixer # фиксит лишние переносы в конце файла
      - id: double-quote-string-fixer # переводит двойные кавычки в одинарные
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort # сортировка импортов в правильном порядке в коде
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a5
    hooks:
      - id: pyproject-flake8 # проверяет длину строки по PEP8 и пропуски между функциями, классами
        name: flake8
        description: 'A monkey patching wrapper to connect flake8 with pyproject.toml configuration'
        entry: pflake8
        language: python
        types: [python]
        require_serial: true
